### ISSUE TITLE
doesn't work on firefox

### ISSUE THREAD

**Issue by lovasoa** [jhildenbiddle/canvas-size#12]
Hello,
 Here is what the demo gives on my firefox: 
![image](https://user-images.githubusercontent.com/552629/113522154-9dd0a480-959e-11eb-93a8-b977d48bd59f.png)

However, the max area supported on this firefox is 11181 x 11181

I think there is an issue with the order in which values are specified in the tests:
https://github.com/jhildenbiddle/canvas-size/blob/master/src/test-sizes.js#L11-L15

**Comment by jhildenbiddle** [comment]
Thanks, @lovasoa. I'll take a look at this over the weekend.
