### ISSUE TITLE
Webpack optimize CanvasTest error

### ISSUE THREAD

**Issue by nicoja** [jhildenbiddle/canvas-size#6]
Hi, first thanks for your work.

I just tried it, and if I specify in webpack.config.js :

```
module.exports = {
    optimization: {
        minimize: true,
        minimizer: [new TerserPlugin(),
    },
...
```

This error is thrown : 
```
Uncaught ReferenceError: canvasTest is not defined
    at onmessage (d6ce07e3-5a07-454b-9558-b3c8698cbe7a:4)
```

I just test this code : 
```
canvasSize.maxArea({
    usePromise: true,
    useWorker : true,
})
    .then(({ width, height, benchmark }) => {
        console.log(`Success: ${width} x ${height} (${benchmark} ms)`);
    })
    .catch(({ width, height, benchmark }) => {
        console.log(`Error: ${width} x ${height} (${benchmark} ms)`);
    });
```

Did I miss something ?

Best regards

**Comment by nicoja** [comment]
The code below works but not the previous one :

```
canvasSize.maxArea({
    onError: function(width, height, benchmark) {
        console.log('Error', width, height, benchmark);
    },
    onSuccess: function(width, height, benchmark) {
        console.log('Success', width, height, benchmark);
    }
});
```

**Comment by jhildenbiddle** [comment]
Hey @nicoja.

I'm not seeing any issues using the code above in basic demo (see code below). My guess is that there is something else in your webpack config that is causing the issue. Try removing plugins and configuration options to see if you can identify the cause of the issue.

**/package.json**

```json
{
  "name": "canvas-size-6",
  "main": "index.js",
  "scripts": {
    "build": "webpack-cli --entry ./index.js -o ./public/",
    "serve": "http-server ./public"
  },
  "devDependencies": {
    "canvas-size": "^1.2.0",
    "http-server": "^0.12.3",
    "terser-webpack-plugin": "^5.0.3",
    "webpack": "^5.4.0",
    "webpack-cli": "^4.1.0"
  }
}
```

**/webpack.config.js**

```js
const TerserPlugin = require('terser-webpack-plugin');

module.exports = {
  optimization: {
    minimize: true,
    minimizer: [
        new TerserPlugin()
    ],
  },
};
```

**/index.js**

```js
import canvasSize from 'canvas-size';

canvasSize.maxArea({
    usePromise: true,
    useWorker : true,
})
.then(({ width, height, benchmark }) => {
    console.log(`Success: ${width} x ${height} (${benchmark} ms)`);
})
.catch(({ width, height, benchmark }) => {
    console.log(`Error: ${width} x ${height} (${benchmark} ms)`);
});
```

**/public/index.html**

```html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>canvas-size - Issue #6</title>
</head>
<body>
    <p>Check console</p>
    <script src="main.js"></script>
</body>
</html>
```

Create these four files, then run the following command to build and serve:

```bash
npm run build
npm run serve
```

**Comment by nicoja** [comment]
Hi @jhildenbiddle thanks for reply.

I try he example you provided and still have the error.
But I have the error only on Chrome, on Firefox it is ok.

Thus I deactivate all my plugins on Chrome and restart it (yes I did it ;)).
Still same problem.

Locally I have : node v11.14.0 (npm v6.14.8)
Chrome : Version 86.0.4240.183 (Build officiel) (x86_64)

Do you use/try Chrome ?

**Comment by jhildenbiddle** [comment]
Very interesting. Also, very confusing.

* The error occurs in Chrome 69 and later on the desktop (tested on macOS & Windows)
* The error does *not* occur in the latest version of Chrome (86) when 
  * ... bundled via Parcel on codesandbox.io: https://c23pn.csb.app/
  * ... when testing in headless mode (tested on macOS & Linux)

The reason I didn't se the issue is because I hadn't tested using Chrome on the desktop. Instead, I tested everything but that: using Safari on the desktop, using Chrome in headless mode, and with sample code on code sandbox.io. 🤦 

Looks like I'll need to dive into this a bit more. Thanks for your patience!

**Comment by jhildenbiddle** [comment]
Hey again, @nicoja.

Turned out to be an issue with [Terser's](https://github.com/terser/terser) `mangle` option. Disabling this feature to reserving the `canvasTest` name in the Terser config appears to have resolved the issue. If you're still having issues, let me know.

Thanks!
